name: AI Research Index Update

on:
  # Run every Wednesday at midnight UTC
  schedule:
    - cron: '0 0 * * 3'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate-research-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for potential commits
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_research_generator/requirements.txt
      
      - name: Create image directories
        run: |
          mkdir -p img/ai-research
          mkdir -p img/profile
          
          # If image directories don't exist, create placeholder files to prevent errors
          if [ ! -f "img/profile/michael-ditter-headshot.jpg" ]; then
            touch img/profile/michael-ditter-headshot.jpg
          fi
      
      - name: Generate AI Research Index
        id: generate_index
        continue-on-error: true
        env:
          # Use the file data source for now
          DATA_SOURCE_TYPE: "file"
          
          # Output configuration
          OUTPUT_HTML_PATH: "blog/ai-research-index.html"
          CANONICAL_URL: "https://www.michaelditter.com/blog/ai-research-index.html"
        run: |
          # Print configuration
          echo "Using DATA_SOURCE_TYPE: $DATA_SOURCE_TYPE"
          echo "Using OUTPUT_HTML_PATH: $OUTPUT_HTML_PATH"
          
          # Generate the HTML
          python ai_research_generator/generate_research_page.py
      
      - name: Fallback to file data if API fails
        if: steps.generate_index.outcome == 'failure'
        env:
          DATA_SOURCE_TYPE: "file"
          OUTPUT_HTML_PATH: "blog/ai-research-index.html"
          CANONICAL_URL: "https://www.michaelditter.com/blog/ai-research-index.html"
        run: |
          echo "API data fetch failed, falling back to file-based data"
          python ai_research_generator/generate_research_page.py
          
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet blog/ai-research-index.html || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add blog/ai-research-index.html
          git commit -m "Update AI Research Index - $(date +'%Y-%m-%d')"
          git push 