name: Link Check
on:
  schedule:
    - cron: "0 12 * * 1"    # weekly on Monday at 12:00 UTC
  workflow_dispatch:         # allow manual trigger
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write          # allow creating issues
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_research_generator/requirements.txt
          
      - name: Run link validator
        id: linkcheck
        run: |
          python -m ai_research_generator.validate_links
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Create issue for broken links
        if: steps.linkcheck.outputs.exit_code != '0'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Broken Links in AI Research Index"
          content-filepath: ./ai_research_generator/link_report.txt
          labels: "broken-link, automated-report" 